/**
 * Códigos de error estables de la API. El frontend traduce por código, nunca por mensaje.
 */
export const ERROR_CODES = [
  'BAD_REQUEST',
  'VALIDATION_ERROR',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'CSRF_REJECTED',
  'NOT_FOUND',
  'METHOD_NOT_ALLOWED',
  'CONFLICT',
  'IDEMPOTENCY_CONFLICT',
  'INVALID_STATE',
  'PRICE_CHANGED',
  'PRODUCT_UNAVAILABLE',
  'LIMIT_EXCEEDED',
  'BLOCKED',
  'ORDER_EXPIRED',
  'PAYLOAD_TOO_LARGE',
  'UNSUPPORTED_MEDIA_TYPE',
  'RATE_LIMITED',
  'MAINTENANCE_MODE',
  'CHECKOUT_DISABLED',
  'PAYMENTS_DISABLED',
  'FULFILLMENT_DISABLED',
  'PAYMENT_PROVIDER_UNAVAILABLE',
  'AUTH_NOT_CONFIGURED',
  'PLAYER_LOOKUP_UNAVAILABLE',
  'PLAYER_NOT_FOUND',
  'PLAYER_LOOKUP_EXPIRED',
  'PLAYER_CONFIRMATION_REQUIRED',
  'MFA_REQUIRED',
  'MFA_INVALID',
  'INVALID_SIGNATURE',
  'SERVICE_UNAVAILABLE',
  'INTERNAL_ERROR',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    message: string;
    requestId: string;
  };
}
